#! /bin/zsh
source activate swin
python encoding_files.py --split train_split/00000.txt &
python encoding_files.py --split train_split/00001.txt &
python encoding_files.py --split train_split/00002.txt &
python encoding_files.py --split train_split/00003.txt &
python encoding_files.py --split train_split/00004.txt &
python encoding_files.py --split train_split/00005.txt &
python encoding_files.py --split train_split/00006.txt &
python encoding_files.py --split train_split/00007.txt &
python encoding_files.py --split train_split/00008.txt &
python encoding_files.py --split train_split/00009.txt &
python encoding_files.py --split train_split/00010.txt &
python encoding_files.py --split train_split/00011.txt &
python encoding_files.py --split train_split/00012.txt &
python encoding_files.py --split train_split/00013.txt &
python encoding_files.py --split train_split/00014.txt &
python encoding_files.py --split train_split/00015.txt &
python encoding_files.py --split train_split/00016.txt &
python encoding_files.py --split train_split/00017.txt &
python encoding_files.py --split train_split/00018.txt &
python encoding_files.py --split train_split/00019.txt &
python encoding_files.py --split train_split/00020.txt &
python encoding_files.py --split train_split/00021.txt &
python encoding_files.py --split train_split/00022.txt &
python encoding_files.py --split train_split/00023.txt &
python encoding_files.py --split train_split/00024.txt &
python encoding_files.py --split train_split/00025.txt &
python encoding_files.py --split train_split/00026.txt &
python encoding_files.py --split train_split/00027.txt &
python encoding_files.py --split train_split/00028.txt &
python encoding_files.py --split train_split/00029.txt &
python encoding_files.py --split train_split/00030.txt &
python encoding_files.py --split train_split/00031.txt &
python encoding_files.py --split train_split/00032.txt &
python encoding_files.py --split train_split/00033.txt &
python encoding_files.py --split train_split/00034.txt &
python encoding_files.py --split train_split/00035.txt &
python encoding_files.py --split train_split/00036.txt &
python encoding_files.py --split train_split/00037.txt &
python encoding_files.py --split train_split/00038.txt &
python encoding_files.py --split train_split/00039.txt &
python encoding_files.py --split train_split/00040.txt &
python encoding_files.py --split train_split/00041.txt &
python encoding_files.py --split train_split/00042.txt &
python encoding_files.py --split train_split/00043.txt &
python encoding_files.py --split train_split/00044.txt &
python encoding_files.py --split train_split/00045.txt &
python encoding_files.py --split train_split/00046.txt &
python encoding_files.py --split train_split/00047.txt &
python encoding_files.py --split train_split/00048.txt &
python encoding_files.py --split train_split/00049.txt &
python encoding_files.py --split train_split/00050.txt &
python encoding_files.py --split train_split/00051.txt &
python encoding_files.py --split train_split/00052.txt &
python encoding_files.py --split train_split/00053.txt &
python encoding_files.py --split train_split/00054.txt &
python encoding_files.py --split train_split/00055.txt &
python encoding_files.py --split train_split/00056.txt &
